name: Advanced Simulation Generator

on:
  workflow_dispatch:
    inputs:
      water:
        description: 'Number of water molecules'
        required: true
        default: '400'
        type: number
      xenon:
        description: 'Number of xenon atoms'
        required: true
        default: '20'
        type: number
        
permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          
      - name: Install basic dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy matplotlib moviepy
      
      - name: Install RDKit
        run: pip install rdkit-pypi
      
      - name: Install PySCF dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libopenblas-dev libxc-dev cmake
      
      - name: Install PySCF
        run: |
          pip install pyscf
          # Verify installation
          python -c "import pyscf; print('PySCF version:', pyscf.__version__)"
          
      - name: Create assets directory
        run: mkdir -p assets
          
      - name: Run simulation without quantum calculations
        run: |
          echo "Running simulation with ${{ github.event.inputs.water }} water molecules and ${{ github.event.inputs.xenon }} xenon atoms"
          python scripts/process.py --water ${{ github.event.inputs.water }} --xenon ${{ github.event.inputs.xenon }} --output assets/simulation_w${{ github.event.inputs.water }}_x${{ github.event.inputs.xenon }}.mp4
          
      - name: Create default video if needed
        run: |
          if [ ! -f assets/default.mp4 ]; then
            cp assets/simulation_w${{ github.event.inputs.water }}_x${{ github.event.inputs.xenon }}.mp4 assets/default.mp4
          fi
          
      - name: Update videos.json
        run: |
          if [ ! -f assets/videos.json ]; then
            echo '{"videos":[]}' > assets/videos.json
          fi
          
          # Add the new video to the list
          python - <<EOF
          import json
          
          # Load current videos.json
          with open('assets/videos.json', 'r') as f:
              data = json.load(f)
          
          # Check if this video is already in the list
          water = ${{ github.event.inputs.water }}
          xenon = ${{ github.event.inputs.xenon }}
          video_file = f"simulation_w{water}_x{xenon}.mp4"
          
          # Check if video already exists in the list
          exists = False
          for video in data["videos"]:
              if video["water"] == water and video["xenon"] == xenon:
                  exists = True
                  break
          
          # Add the video if it doesn't exist
          if not exists:
              data["videos"].append({
                  "water": water,
                  "xenon": xenon,
                  "file": video_file
              })
          
          # Write the updated JSON back
          with open('assets/videos.json', 'w') as f:
              json.dump(data, f, indent=2)
          EOF
          
      - name: Commit and push new files
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add assets/simulation_w${{ github.event.inputs.water }}_x${{ github.event.inputs.xenon }}.mp4
          git add assets/videos.json
          if [ ! -f assets/default.mp4 ]; then
            git add assets/default.mp4
          fi
          git commit -m "Add simulation video: water=${{ github.event.inputs.water }}, xenon=${{ github.event.inputs.xenon }}"
          git push
